package core

import (
	"runtime"
	"strconv"
	"testing"
	"time"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// BenchmarkSnapshotRetention measures the heap retained by holding several
// decoded copies of a synthetic monorepo snapshot plus a scan cache for the
// same tree, which is the shape of a single synchronization session's
// steady-state memory.
//
// Retention is measured with ReadMemStats deltas across forced garbage
// collections because testing.B's allocation counters measure churn, not
// retention. Each iteration measures and then drops an independent set of
// trees, so the reported metrics are per-iteration averages and the iteration
// count doesn't multiply peak memory. Run with -benchtime=1x for a single clean
// measurement.
func BenchmarkSnapshotRetention(b *testing.B) {
	// Build the synthetic tree and encode it, along with a cache covering the
	// same tree. Both are encoded once so that each measurement pays only for
	// decoding.
	tree := buildSyntheticTree(syntheticTreeFileCount)
	archiveBytes, err := proto.Marshal(&Archive{Content: tree.root})
	if err != nil {
		b.Fatal("unable to marshal archive:", err)
	}
	cacheBytes, err := proto.Marshal(tree.buildCache())
	if err != nil {
		b.Fatal("unable to marshal cache:", err)
	}

	// Log the corpus shape so that reported metrics can be extrapolated.
	b.Logf("%d files, %d directories, %d distinct digests, %d-byte archive, %d-byte cache",
		tree.files, tree.directories, tree.distinctDigests, len(archiveBytes), len(cacheBytes),
	)

	// Benchmark each intern table lifecycle.
	for _, strategy := range []struct {
		name string
		mode interningMode
	}{
		{"Baseline", interningNone},
		{"PerPassTable", interningPerPass},
		{"PerSessionTable", interningPerSession},
	} {
		b.Run(strategy.name, func(b *testing.B) {
			var retainedBytes, retainedObjects uint64
			for i := 0; i < b.N; i++ {
				// Measure the live heap before decoding.
				b.StopTimer()
				baseBytes, baseObjects := liveHeap()
				b.StartTimer()

				// Decode a session's worth of state, interning as requested. A
				// per-session table is dropped before measurement to confirm
				// that sharing outlives the table that established it.
				held := decodeSessionState(b, archiveBytes, cacheBytes, strategy.mode)

				// Measure the live heap with the decoded state held.
				b.StopTimer()
				heldBytes, heldObjects := liveHeap()
				retainedBytes += heldBytes - baseBytes
				retainedObjects += heldObjects - baseObjects
				b.StartTimer()

				// Release the decoded state for the next iteration.
				runtime.KeepAlive(held)
				held = nil
			}

			// Report retention.
			iterations := float64(b.N)
			b.ReportMetric(float64(retainedBytes)/iterations/(1<<20), "MB_retained")
			b.ReportMetric(float64(retainedObjects)/iterations, "live_objects")
			b.ReportMetric(float64(retainedBytes)/iterations/float64(tree.files), "B/file")
		})
	}
}

// BenchmarkInternEntries measures a single interning pass over a decoded
// snapshot, which is the per-cycle cost that interning adds to a scan or a
// snapshot receive.
func BenchmarkInternEntries(b *testing.B) {
	// Build the synthetic tree.
	tree := buildSyntheticTree(syntheticTreeFileCount)

	// Report allocations, since the intern table is transient garbage.
	b.ReportAllocs()

	// Reset the benchmark timer to exclude the setup time.
	b.ResetTimer()

	// Perform the benchmark.
	for i := 0; i < b.N; i++ {
		NewDigestInterner(0).InternEntries(tree.root)
	}
}

const (
	// syntheticTreeFileCount is the number of file entries generated by the
	// synthetic tree used in retention benchmarks. It's large enough for
	// per-file overhead to dominate fixed costs and for retention deltas to sit
	// well above measurement noise, but small enough to keep the benchmark
	// runnable on a laptop.
	syntheticTreeFileCount = 150000

	// syntheticTreeSnapshotCopies is the number of independently decoded copies
	// of the synthetic tree held during retention benchmarks. It models the
	// ancestor, alpha, and beta trees that a session retains simultaneously.
	syntheticTreeSnapshotCopies = 3
)

// interningMode determines the intern table lifecycle used when decoding a
// session's worth of state.
type interningMode uint8

const (
	// interningNone decodes without interning, i.e. current behavior.
	interningNone interningMode = iota
	// interningPerPass uses a fresh intern table for each decoded tree, which
	// deduplicates digests only within a single tree.
	interningPerPass
	// interningPerSession uses one intern table for all of a session's trees,
	// modeling interning against a seed drawn from live state.
	interningPerSession
)

// decodeSessionState decodes a session's worth of state (several copies of a
// snapshot plus a cache) and returns it for retention measurement.
func decodeSessionState(b *testing.B, archiveBytes, cacheBytes []byte, mode interningMode) []any {
	// Create the per-session intern table, if requested.
	var session *DigestInterner
	if mode == interningPerSession {
		session = NewDigestInterner(0)
	}

	// interner returns the table to use for the next decoded message, which is
	// a fresh table per pass unless a session-wide table is in use.
	interner := func() *DigestInterner {
		if mode == interningPerSession {
			return session
		} else if mode == interningPerPass {
			return NewDigestInterner(0)
		}
		return nil
	}

	// Decode the snapshot copies.
	held := make([]any, 0, syntheticTreeSnapshotCopies+1)
	for c := 0; c < syntheticTreeSnapshotCopies; c++ {
		archive := &Archive{}
		if err := proto.Unmarshal(archiveBytes, archive); err != nil {
			b.Fatal("unable to unmarshal archive:", err)
		}
		if table := interner(); table != nil {
			table.InternEntries(archive.Content)
		}
		held = append(held, archive)
	}

	// Decode the cache.
	cache := &Cache{}
	if err := proto.Unmarshal(cacheBytes, cache); err != nil {
		b.Fatal("unable to unmarshal cache:", err)
	}
	if table := interner(); table != nil {
		table.InternCache(cache)
	}
	held = append(held, cache)

	// Done.
	return held
}

// liveHeap returns the number of live heap bytes and live heap objects after a
// full garbage collection cycle. Two cycles are performed because a single
// cycle can leave memory whose freeing is deferred to the next cycle.
func liveHeap() (bytes uint64, objects uint64) {
	runtime.GC()
	runtime.GC()
	var stats runtime.MemStats
	runtime.ReadMemStats(&stats)
	return stats.HeapAlloc, stats.HeapObjects
}

// syntheticTree is a generated directory hierarchy along with statistics about
// its contents.
type syntheticTree struct {
	// root is the root entry of the hierarchy.
	root *Entry
	// files is the number of file entries in the hierarchy.
	files int
	// directories is the number of directory entries in the hierarchy.
	directories int
	// distinctDigests is the number of distinct file digests in the hierarchy.
	distinctDigests int
}

// buildSyntheticTree generates a monorepo-shaped entry hierarchy with the
// requested number of file entries. Directories nest between three and eight
// levels deep, basenames repeat heavily across directories, and a fraction of
// files share content digests, as empty and generated files do in a real
// repository.
func buildSyntheticTree(files int) *syntheticTree {
	// Create the generator state.
	generator := &syntheticTreeGenerator{
		random:          newSplitMix64(0x5DEECE66D),
		remaining:       files,
		digestsByBucket: make(map[uint64][]byte),
	}

	// Generate the hierarchy, extending it until the file budget is exhausted.
	root := &Entry{Contents: make(map[string]*Entry)}
	generator.directories++
	for pass := 0; generator.remaining > 0; pass++ {
		name := "root" + strconv.Itoa(pass)
		root.Contents[name] = generator.directory(1)
	}

	// Done.
	return &syntheticTree{
		root:            root,
		files:           files - generator.remaining,
		directories:     generator.directories,
		distinctDigests: len(generator.digestsByBucket),
	}
}

// buildCache generates a scan cache covering every file in the hierarchy, keyed
// by full path. Its digests are copies rather than aliases of the hierarchy's
// digests, matching what a cache loaded from disk looks like.
func (t *syntheticTree) buildCache() *Cache {
	// Create the cache.
	cache := &Cache{Entries: make(map[string]*CacheEntry, t.files)}

	// Add an entry for every file in the hierarchy, synthesizing plausible
	// metadata from a counter.
	var count uint64
	t.root.walk("", func(path string, entry *Entry) {
		if entry == nil || entry.Kind != EntryKind_File {
			return
		}
		count++
		cache.Entries[path] = &CacheEntry{
			Mode:             0644,
			ModificationTime: timestamppb.New(time.Unix(1600000000+int64(count), 0)),
			Size:             count,
			FileID:           count,
			Digest:           append([]byte(nil), entry.Digest...),
		}
	}, false)

	// Done.
	return cache
}

// syntheticTreeGenerator holds the state used while generating a synthetic
// tree.
type syntheticTreeGenerator struct {
	// random is the pseudo-random number source.
	random *splitMix64
	// remaining is the number of file entries still to be generated.
	remaining int
	// directories is the number of directory entries generated so far.
	directories int
	// digestsByBucket maps content bucket identifiers to the digest generated
	// for that bucket, which is how repeated file content is modeled.
	digestsByBucket map[uint64][]byte
}

// directory generates a directory entry at the specified depth, consuming from
// the generator's remaining file budget.
func (g *syntheticTreeGenerator) directory(depth int) *Entry {
	// Record the directory.
	g.directories++

	// Create the directory entry.
	result := &Entry{Contents: make(map[string]*Entry)}

	// Add files, drawing from the repeated basename pool and adding a numeric
	// suffix only when a name would collide within this directory.
	fileCount := 4 + int(g.random.next()%12)
	for f := 0; f < fileCount && g.remaining > 0; f++ {
		name := syntheticFileNames[int(g.random.next()%uint64(len(syntheticFileNames)))]
		if _, ok := result.Contents[name]; ok {
			name = strconv.Itoa(f) + "_" + name
		}
		result.Contents[name] = &Entry{
			Kind:   EntryKind_File,
			Digest: g.digest(),
		}
		g.remaining--
	}

	// Stop recursing once the depth limit is reached.
	if depth >= 8 || (depth >= 3 && g.random.next()%4 == 0) {
		return result
	}

	// Recurse into subdirectories.
	subdirectoryCount := 2 + int(g.random.next()%3)
	for s := 0; s < subdirectoryCount && g.remaining > 0; s++ {
		name := syntheticDirectoryNames[int(g.random.next()%uint64(len(syntheticDirectoryNames)))]
		if _, ok := result.Contents[name]; ok {
			name = name + strconv.Itoa(s)
		}
		result.Contents[name] = g.directory(depth + 1)
	}

	// Done.
	return result
}

// digest generates a digest for a file, drawing from a small pool of shared
// content digests roughly a tenth of the time and generating unique content
// otherwise. Each file receives its own copy of the digest bytes, which is what
// Protocol Buffers decoding produces.
func (g *syntheticTreeGenerator) digest() []byte {
	// Determine the content bucket. Buckets below syntheticSharedContentCount
	// are shared between files, all others are unique.
	var bucket uint64
	if g.random.next()%10 == 0 {
		bucket = g.random.next() % syntheticSharedContentCount
	} else {
		bucket = syntheticSharedContentCount + uint64(len(g.digestsByBucket))
	}

	// Generate the digest for the bucket if this is its first use.
	digest, ok := g.digestsByBucket[bucket]
	if !ok {
		digest = make([]byte, syntheticDigestLength)
		for i := range digest {
			digest[i] = byte(g.random.next())
		}
		g.digestsByBucket[bucket] = digest
	}

	// Done.
	return append([]byte(nil), digest...)
}

const (
	// syntheticDigestLength is the digest length generated for synthetic trees.
	// It matches XXH128, Mutagen's default hashing algorithm.
	syntheticDigestLength = 16

	// syntheticSharedContentCount is the number of distinct content digests
	// shared between multiple synthetic files.
	syntheticSharedContentCount = 64
)

// syntheticFileNames are the basenames used for synthetic file entries. They
// repeat heavily across directories, as they do in a real monorepo.
var syntheticFileNames = []string{
	"BUILD.bazel", "__init__.py", "README.md", "main.go", "doc.go",
	"types.ts", "index.ts", "conftest.py", "handler.go", "handler_test.go",
	"schema.json", "Makefile", "test_util.py", "constants.py", "utils.go",
}

// syntheticDirectoryNames are the basenames used for synthetic directory
// entries.
var syntheticDirectoryNames = []string{
	"pkg", "internal", "cmd", "server", "client", "api", "core", "utils",
	"tests", "docs", "proto", "web", "src", "lib", "tools",
}

// splitMix64 is a deterministic pseudo-random number generator. It's used
// instead of math/rand so that generated trees are stable across Go releases.
type splitMix64 struct {
	state uint64
}

// newSplitMix64 creates a generator with the specified seed.
func newSplitMix64(seed uint64) *splitMix64 {
	return &splitMix64{state: seed}
}

// next returns the next value in the sequence.
func (r *splitMix64) next() uint64 {
	r.state += 0x9E3779B97F4A7C15
	z := r.state
	z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
	z = (z ^ (z >> 27)) * 0x94D049BB133111EB
	return z ^ (z >> 31)
}
